@startuml
'https://plantuml.com/class-diagram

class NoOpAuthenticationManager
class ProviderManager
interface AuthenticationManager


AuthenticationManager <|.. ProviderManager
AuthenticationManager <|.. NoOpAuthenticationManager


@enduml