@startuml
'https://plantuml.com/class-diagram

class NoOpPasswordEncoder
class BCryptPasswordEncoder
class DelegatingPasswordEncoder
interface PasswordEncoder


PasswordEncoder <|.. NoOpPasswordEncoder
PasswordEncoder <|.. BCryptPasswordEncoder
PasswordEncoder <|.. DelegatingPasswordEncoder


@enduml